apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: synsmart-api-secrets
  namespace: default
spec:
  provider: azure
  parameters:
    keyvaultName: "synsmart-keyvault"
    clientID: "27e9fca2-e829-4dcf-bc42-2217aee4f12b"
    objects: |
      array:
        - |
          objectName: blob-storage-account-connection-string
          objectType: secret
        - |
          objectName: cognitive-search-primary-key
          objectType: secret
        - |
          objectName: azure-client-id
          objectType: secret
        - |
          objectName: azure-tenant-id
          objectType: secret
        - |
          objectName: phenix-slack-bot-user-id
          objectType: secret
    tenantId: "b8330290-6545-43b3-ad74-84d7078a8743"
  secretObjects:
    - secretName: synsmart-api-app-secrets
      type: Opaque
      data:
        - objectName: blob-storage-account-connection-string
          key: BLOB_STORAGE_CONNECTION_STRING
        - objectName: cognitive-search-primary-key
          key: COGNITIVE_SEARCH_ADMIN_KEY
        - objectName: azure-client-id
          key: AZURE_CLIENT_ID
        - objectName: azure-tenant-id
          key: AZURE_TENANT_ID
        - objectName: phenix-slack-bot-user-id
          key: PHENIX_SLACK_BOT_USER_ID
